### ISSUE TITLE
Replace EzXML with LightXML

### ISSUE THREAD

**Issue by mirestrepo** [BioJulia/BioServices.jl#10]
@bicycle1885 EzXML has not been building in Linux since Julia 0.6.3 and the [issue](https://github.com/bicycle1885/EzXML.jl/issues/65) has not been addressed. The xml functionality needed for EUtils is minimal. Do you oppose if we switch BioServices to use LightXML? Or are you actively working on EzXML?

**Comment by BenJWard** [comment]
It's actually utlimately up to you as the BioJulia/BioServices maintainer 😄.
EzXML improves on some some the previous XML library interface packages.
Kenta is the maintainer of EzXML, but I also know Kenta is likely very busy with PhD or related activities.
There's always the possibility of changing it back if EzXML gets fixed.
With a package such as EzXML I would have thought the pressure would be high for someone else to make a fix and PR if Kenta is too time constrained.

**Comment by BenJWard** [comment]
@mirestrepo FYI, work to fix EzXML is currently going on here: https://github.com/bicycle1885/EzXML.jl/pull/68#issuecomment-399775597

**Comment by fernandogelin** [comment]
@mirestrepo I submitted a PR that addresses this issue.

**Comment by bicycle1885** [comment]
I'm sorry for being late. The blocker of EzXML.jl is in [XML2Builder](https://github.com/bicycle1885/XML2Builder), and some people trying to fix that (see https://github.com/bicycle1885/XML2Builder/pull/8, for example). I'm not sure whether it will be fixed very soon, and I have very little time to work on this problem at least for next a few weeks. So, feel free to change it to another package if you need.

**Comment by mirestrepo** [comment]
I have merged #11 and will close this. If in the future we want to revert back to EzXML we can easily do that - the xml parsing done by the EUtils is very minimal
