### ISSUE TITLE
Error 414 Request-URI Too Large

### ISSUE THREAD

**Issue by mcmcgrath13** [BioJulia/BioServices.jl#19]
## Expected Behavior

When using eFetch (via BioMedQuery), should return results.  This is for a simple query (e.g. `term="asthma"[mh:noexp]`), which is not very long.

## Current Behavior

HTTP returns a 414 error saying the URI was too long.  With postman, this did work.

## Steps to Reproduce (for bugs)

`BioMedQuery.Processes.pubmed_search_and_parse("", """("asthma"[mh:noexp])""", 999999999999)`

Which calls:
```
using XMLDict
using BioServices.EUtils

rs = 0
retmax = 10000
term = """"asthma"[mh:noexp]"""
email = ""

search_response = esearch(db = "pubmed", term = search_term,
        retstart = rs, retmax = retmax, tool = "BioJulia",
        email = email)

        # if verbose
        #     xdoc = parse_string(esearch_response)
        #     save_file(xdoc, "./esearch.xml")
        # end

        #convert xml to dictionary
        esearch_dict = parse_xml(String(esearch_response.body))

        if !haskey(esearch_dict, "IdList")
            println("Error with esearch_dict:")
            println(esearch_dict)
            error("Response esearch_dict does not contain IdList")
        end

        println("------EFetch--------")

        #get the list of ids and perfom a fetch
        ids = [parse(Int64, id_node) for id_node in esearch_dict["IdList"]["Id"]]

        efetch_response = efetch(db = "pubmed", tool = "BioJulia", retmode = "xml", rettype = "null", id = ids)
```

## Context

Trying to get articles related to a mesh term for further processing.  This is the first step.

## Your Environment

- Package Version used: 0.3.0
- Julia Version used: 0.7
- Operating System and version (desktop or mobile): mac osx 10.13
- Link to your project: https://github.com/bcbi/PubMedMiner.jl

**Comment by mcmcgrath13** [comment]
I believe this is because efetch is passing the IDs in the query of the URI instead of the body

**Comment by mirestrepo** [comment]
For reference.. we'll work on this tomorrow. This [discussion](https://github.com/JuliaWeb/HTTP.jl/issues/243) maybe useful.

We may just need to change the POST call from
`HTTP.request("POST", url, query=body) ` to
`HTTP.request("POST", url, body=body)`
