### ISSUE TITLE
Errors on master with testing and ci

### ISSUE THREAD

**Issue by BenJWard** [BioJulia/BioServices.jl#21]
Tests and CI should not error.
But current behaviour is as seen in https://travis-ci.org/BioJulia/BioServices.jl/jobs/437751090 
Is anyone else experiencing this?

**Comment by jgreener64** [comment]
There's a similar error for BioStructures: https://travis-ci.org/BioJulia/BioStructures.jl/jobs/442584453
Looks like the autobuild process is having trouble connecting to the internet?

**Comment by BenJWard** [comment]
I also have issues on my desktop, so I don't think it is travis specific

**Comment by mirestrepo** [comment]
I have merge #24 to help. HTTP requests have a strange behavior at times - adding a retry helps but it also gets us in trouble with rate limits for requests. We'll continue to look into this in the future as HTTP.jl continues to mature
